# Generated by Django 4.2 on 2024-04-14 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_category_created_at_alter_category_updated_at_and_more'),
        ('sales_basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='sales',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.variant'),
            preserve_default=False,
        ),
    ]
