# Generated by Django 4.2 on 2024-04-15 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0027_alter_category_created_at_alter_category_updated_at_and_more'),
        ('sales_basket', '0002_sales_quantity_sales_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد خرید'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.variant', verbose_name='تنوع'),
        ),
    ]
