# Generated by Django 4.2 on 2024-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کاربری'),
        ),
    ]
