# Generated by Django 4.2 on 2024-04-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first',
        ),
    ]
