# Generated by Django 4.2 on 2024-04-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_cat',
            field=models.CharField(blank=True, choices=[('ویولن', 'ویولن'), ('ویولا', 'ویولا'), ('چلو', 'چلو'), ('کنترباس', 'کنترباس'), ('گیتار الکتریک', 'گیتار الکتریک'), ('گیتار آکوستیک', 'گیتار آکوستیک'), ('گیتار', 'گیتار'), ('فلوت', 'فلوت'), ('کلارینت', 'کلارینت'), ('دودوک', 'دودوک'), ('ابوا', 'ابوا'), ('ساکسیفون', 'ساکسیفون'), ('ترومپت', 'ترومپت'), ('ترومبون', 'ترومبون'), ('هورن', 'هورن'), ('توبا', 'توبا')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='نام'),
        ),
    ]
