# Generated by Django 4.2 on 2024-04-01 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_sub_cat_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='shop.category', verbose_name='ریز دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_cat',
            field=models.BooleanField(default=False, verbose_name='آیا ریز دسته بندی هست؟'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.category', verbose_name='دسته بندی'),
        ),
    ]
