# Generated by Django 4.2 on 2024-04-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_sub_category_alter_category_sub_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_cat',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='shop.category', verbose_name='ریز دسته بندی')),
            ],
            options={
                'verbose_name': 'ریز دسته بندی',
                'verbose_name_plural': 'ریز دسته بندی\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='shop.sub_category', verbose_name='دسته بندی'),
        ),
    ]
