# Generated by Django 4.2 on 2024-04-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_category_sub_cat_remove_category_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
