# Generated by Django 4.2 on 2024-04-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='shop.sub_category', verbose_name='دسته بندی'),
        ),
    ]
