# Generated by Django 4.2 on 2024-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_color_size_product_status_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=3, unique=True, verbose_name='سایز'),
        ),
    ]
