# Generated by Django 4.2 on 2024-04-07 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size', verbose_name='سایز'),
        ),
    ]
