# Generated by Django 4.2 on 2024-04-10 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_comment_options_alter_imagegallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
