# Generated by Django 4.2 on 2024-04-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='product',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
