# Generated by Django 4.2 on 2024-04-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_category_created_at_alter_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=3, verbose_name='سایز'),
        ),
    ]
