# Generated by Django 4.2 on 2024-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('سایز', 'سایز'), ('رنگ', 'رنگ')], max_length=50, null=True),
        ),
    ]
